### ISSUE TITLE
Scala related crash due  to debug GUI

### ISSUE THREAD

**Issue by Water-Moon** [ModularMods/ModularWarfare#11]
One would be getting this crash if they is wearing a piece of golden armor (due to the debug GUI being turned on and it uses the `Arrays` class from `scala`. I suggest replacing `import scala.actors.threadpool.Arrays;` with `import java.util.Arrays;` at [DevGui.java#16](https://github.com/ModularMods/ModularWarfare/blob/5dc89683f67732d76950eb0afa813ec604ddc26a/src/main/java/com/modularwarfare/utility/DevGui.java#L16), due to scala not being supported in some cases.

The exact crash:
```
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
    at com.modularwarfare.utility.DevGui.<init>(DevGui.java:73)
    at com.modularwarfare.client.handler.RenderGuiHandler.onRenderGui(RenderGuiHandler.java:23)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1533_RenderGuiHandler_onRenderGui_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
    at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:609)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:169)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1426)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by MineCinema** [comment]
I also repeatedly got a crash when putting on gold armor.

**Comment by Protoxy22** [comment]
Fixed
